#!/bin/bash

server_up=true;

if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then 
	echo "Website is online"
else
	server_up=false;
	echo "Website it offline"
fi

if ping -c 1 192.168.1.3 > /dev/null; then
	echo "Ping Successful"
else
	server_up=false;
	echo "Ping Unsuccessful"
fi

if ! $server_up; then
	echo "Server down, should initiate services"

declare -i servicesStarted=0;
declare -i reqdServices=2;

	systemctl start nginx
	if systemctl status nginx > /dev/null; then
		echo "nginx started"
		servicesStarted+=1;
	else
		echo "failed to start nginx"
	fi

	systemctl start gunicorn
	if systemctl status gunicorn > /dev/null; then
		echo "gunicorn started"
		servicesStarted+=1;
	else
		echo "failed to start gunicorn"
	fi

	if [ $servicesStarted -eq $reqdServices ]; then
		echo "All services initialized."
		ip addr add 192.168.1.250/24 dev wlo1;
	else
		echo "Only $servicesStarted/$reqdServices services started."
	fi
fi

