#!/bin/bash


FILE_SIZE=$(stat -c %s "/home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog")

if [ $FILE_SIZE -ge 10000000 ]; then
        mv /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog1
fi


server_down=false;

addIPAddress(){
if ip addr add 192.168.1.5/24 dev wlo1; then
	if sudo arping -U -I wlo1 -c 1 192.168.1.5; then
	echo "Succesfully let other devices know of the IP address change."
	else
	echo "Failed to let other devices know of the IP address change."
	fi
	return 0;
elif [ $? -eq 2 ]; then
	echo "Address was already assigned. We can move on"
	if sudo arping -U -I wlo1 -c 1 192.168.1.5; then
	echo "Succesfully let other devices know of the IP address change."
	else
	echo "Failed to let other devices know of the IP address change."
	fi
	return 0;
else
	echo "Couldn't assign the IP address" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	return 1;
fi
}


takeover() {
	echo "Initiate takeover procedure" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	echo "Should initiate services"

declare -i servicesStarted=0;
declare -i reqdServices=2;

	systemctl start nginx
	if systemctl status nginx > /dev/null; then
		echo "NGINX started"
		servicesStarted+=1;
	else
		echo "Failed to start NGINX"
	fi

	systemctl start gunicorn
	if systemctl status gunicorn > /dev/null; then
		echo "Gunicorn started"
		servicesStarted+=1;
	else
		echo "Failed to start Gunicorn"
	fi

	if [ $servicesStarted -eq $reqdServices ]; then
		echo "All services initialized." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;

		if [ ! $server_down ]; then
		echo "Server is down. Let's add the router's port forwarding IP address." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			if addIPAddress; then
				sudo -u susie sh -c 'echo "active" > /tmp/mystate'
				sudo certbot renew -q >> /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog 2>&1 &
				echo "Router's port forwarding IP address was correctly added." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			else
				echo "Router's port forwarding IP address couldn't be correctly added." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			fi

		else
		echo "Server is online. Should ask the server to unassign the IP address" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			if ssh -i /home/susie/.ssh/key_RecoveryMain Gucci@192.168.1.3 'sudo /home/user/recovery_backup/unassignIP'; then
				sudo -u susie sh -c 'echo "active" > /tmp/mystate'

				echo "Main server released the IP address. Adding it now" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
				if addIPAddress; then
				sudo certbot renew -q >> /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog 2>&1 &
				echo "Router's port forwarding IP address was correctly added." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
				else
					echo "Router's port forwarding IP address couldn't be correctly added." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
				fi
			else
					echo "Main server couldn't release the IP address." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
					echo " Couldn't add the IP address. Failover will likely fail on this run." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			fi

		fi
	else
		echo "Only $servicesStarted/$reqdServices services started. Takeover was unsuccessful." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	fi

		echo "Let's sleep 30 and see if the website is online now"
		sleep 30;
		if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
			echo "Website is online. Takeover was successful" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
		else
			echo "Website is offline. Takeover likely failed"
		fi
}


recover_server() {

if ssh -i /home/susie/.ssh/key_RecoveryMain Gucci@192.168.1.3 'sudo /home/user/recovery_backup/recoveryScript'; then
	echo "Recovery code Executed Successfully. Let's wait 30 sec to see if the website comes back" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	sleep 5;
	if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
	echo "The website came back. Recovery was successful" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	else
	echo "After executing the recovery script, the website still didn't come back" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	takeover
	fi
else
	echo "Recovery code couldn't perform the recovery successfully. Let's sleep 10secs and try again" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	sleep 10;

	if ssh -i /home/susie/.ssh/key_RecoveryMain Gucci@192.168.1.3 'sudo /home/user/recovery_backup/recoveryScript'; then
		echo "Recovery code Executed Successfully. Let's wait 30 sec to see if the website comes back" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
		sleep 30;
		if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
			echo "The website came back. Recovery was successful" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
		else
			echo "After executing the recovery script, the website still didn't come back" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			takeover
		fi
else
		takeover
	fi
fi
}

# We start by checking if the website is offline.

if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
# if it is online, go right ahead
	echo "Website is online"
else
echo 1 > /home/susie/myWebsite/Executables/clusterAdmin/lockFile

echo " " >> /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
echo "$(date '+%Y-%m-%d %H:%M:%S')" >> /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
echo "Website is detected to be offline. Let's run checks to reliably confirm that it is down" | tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
# if it is offline, we have to do more checks to see if it is really offline or it was just noise
sleep 3;
# the website will be checked for a total of 10 times. Only If it is unresponsive on all checks, we move on to another section
# the checks will last for a minimum of 30s and the time it takes for curl to return
declare -i webUpCount=1;
declare -i minChecks=5;
	while  ! curl -s -I -f https://www.sushantadk.com/ > /dev/null  && [ $webUpCount -lt $minChecks ]
	do
	echo " Check $webUpCount. Website still down. Sleep for 2secs before continue"
	sleep 2;
	webUpCount+=1;
	done

	if [ $webUpCount -ge $minChecks ]; then
		echo "Website is confirmed to be down after $webUpCount checks" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
		echo "Let's see if we can ping the server"

		if ping -c 1 192.168.1.3 > /dev/null; then
			echo "Ping Successful. This is strange. Website is down but server is up? Let's sleep 10 and check again. Maybe the server just booted." |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			sleep 10;
			if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then 
				echo "The website responded. We are good" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
			else
				echo "The website is dead. Since the server is up, Let's try recovery." | tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
				recover_server
			fi
		else
			echo "Ping Unsuccessful. Let's run more checks to reliably confirm that the server is dead."
		declare -i serverUpCount=1;
		declare -i minChecksServer=5;

			while ! ping -c 1 192.168.1.3 > /dev/null && [ $serverUpCount -lt $minChecksServer ]
			do
			echo " Check $serverUpCount. Server still down. Sleep for 2secs before continue"
			sleep 1;
			serverUpCount+=1;
			done

			if [ $serverUpCount -ge $minChecksServer ]; then
				echo "The server is confirmed dead. Should Take over" | tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
				server_down=true;
				takeover
				# Take Over Here
			else
				echo "The server responded in $serverUpCount checks. Let's try recovery" |  tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
				# Try recovery Here
				recover_server
		fi

	fi
	else
		echo "Website responded after $webUpCount checks. We good" | tee -a /home/susie/myWebsite/Executables/clusterAdmin/clusterAdminLog;
	fi
fi

echo 0 > /home/susie/myWebsite/Executables/clusterAdmin/lockFile
