#!/bin/bash

server_down=false;

addIPAddress(){
if ip addr add 192.168.1.5/24 dev wlo1; then
	if sudo arping -U -I wlo1 -c 1 192.168.1.5; then
	echo "Succesfully let other devices know of the IP address change."
	else
	echo "Failed to let other devices know of the IP address change."
	fi
	return 0;
elif [ $? -eq 2 ]; then
	echo "Address was already assigned. We can move on"
	if sudo arping -U -I wlo1 -c 1 192.168.1.5; then
	echo "Succesfully let other devices know of the IP address change."
	else
	echo "Failed to let other devices know of the IP address change."
	fi
	return 0;
else
	echo "Couldn't assign the IP address"
	return 1;
fi
}


takeover() {

	echo "Should initiate services"

declare -i servicesStarted=0;
declare -i reqdServices=2;

	systemctl start nginx
	if systemctl status nginx > /dev/null; then
		echo "NGINX started"
		servicesStarted+=1;
	else
		echo "Failed to start NGINX"
	fi

	systemctl start gunicorn
	if systemctl status gunicorn > /dev/null; then
		echo "Gunicorn started"
		servicesStarted+=1;
	else
		echo "Failed to start Gunicorn"
	fi

	if [ $servicesStarted -eq $reqdServices ]; then
		echo "All services initialized."

		if [ $server_down ]; then
		echo "Server is down. Let's add the router's port forwarding IP address."
			if addIPAddress; then
				echo "Router's port forwarding IP address was correctly added."
			else
				echo "Router's port forwarding IP address couldn't be correctly added."
			fi

		else
		echo "Server is online. Should ask the server to unassign the IP address"
			if ssh -i /home/susie/.ssh/key_RecoveryMain Gucci@192.168.1.3 'sudo /home/user/recovery_backup/unassignIP'; then
				echo "Main server released the IP address. Adding it now"
				if addIPAddress; then
				echo "Router's port forwarding IP address was correctly added."
				else
					echo "Router's port forwarding IP address couldn't be correctly added."
				fi
			else
					echo "Main server couldn't release the IP address."
					echo " Couldn't add the IP address. Failover will likely fail on this run."
			fi

		fi
	else
		echo "Only $servicesStarted/$reqdServices services started. Takeover was unsuccessful."
	fi

		echo "Let's sleep 30 and see if the website is online now"
		sleep 30;
		if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
			echo "Website is online. Takeover was successful"
		else
			echo "Website is offline. Takeover likely failed"
		fi
}


recover_server() {

if ssh -i /home/susie/.ssh/key_RecoveryMain Gucci@192.168.1.3 'sudo /home/user/recovery_backup/recoveryScript'; then
	echo "Recovery code Executed Successfully. Let's wait 30 sec to see if the website comes back"
	sleep 5;
	if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
	echo "The website came back. Recovery was successful"
	else
	echo "After executing the recovery script, the website still didn't come back"
	takeover
	fi
else
	echo "Recovery code couldn't perform the recovery successfully. Let's sleep 10secs and try again"
	sleep 10;

	if ssh -i /home/susie/.ssh/key_RecoveryMain Gucci@192.168.1.3 'sudo /home/user/recovery_backup/recoveryScript'; then
		echo "Recovery code Executed Successfully. Let's wait 30 sec to see if the website comes back"
		sleep 30;
		if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
			echo "The website came back. Recovery was successful"
		else
			echo "After executing the recovery script, the website still didn't come back"
			takeover
		fi
else
		takeover
	fi
fi
}

# We start by checking if the website is offline.

if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then
# if it is online, go right ahead
	echo "Website is online"
else
echo "Website is detected to be offline. Let's run checks to reliably confirm that it is down"
# if it is offline, we have to do more checks to see if it is really offline or it was just noise
sleep 3;
# the website will be checked for a total of 10 times. Only If it is unresponsive on all checks, we move on to another section
# the checks will last for a minimum of 30s and the time it takes for curl to return
declare -i webUpCount=1;
declare -i minChecks=5;
	while  ! curl -s -I -f https://www.sushantadk.com/ > /dev/null  && [ $webUpCount -lt $minChecks ]
	do
	echo " Check $webUpCount. Website still down. Sleep for 2secs before continue"
	sleep 2;
	webUpCount+=1;
	done

	if [ $webUpCount -ge $minChecks ]; then
		echo "Website is confirmed to be down after $webUpCount checks"
		echo "Let's see if we can ping the server"

		if ping -c 1 192.168.1.3 > /dev/null; then
			echo "Ping Successful. This is strange. Website is down but server is up? Let's sleep 10 and check again. Maybe the server just booted."
			sleep 10;
			if curl -s -I -f https://www.sushantadk.com/ > /dev/null; then 
				echo "The website responded. We are good"
			else
				echo "The website is dead. Since the server is up, Let's try recovery."
				recover_server
			fi
		else
			echo "Ping Unsuccessful. Let's run more checks to reliably confirm that the server is dead."
		declare -i serverUpCount=1;
		declare -i minChecksServer=5;

			while ! ping -c 1 192.168.1.3 > /dev/null && [ $serverUpCount -lt $minChecksServer ]
			do
			echo " Check $serverUpCount. Server still down. Sleep for 2secs before continue"
			sleep 1;
			serverUpCount+=1;
			done

			if [ $serverUpCount -ge $minChecksServer ]; then
				echo "The server is confirmed dead. Should Take over"
				server_down=true;
				takeover
				# Take Over Here
			else
				echo "The server responded in $serverUpCount checks. Let's try recovery"
				# Try recovery Here
			fi

	fi
	else
		echo "Website responded after $webUpCount checks. We good"
	fi
fi
